### PR TITLE
Include Nutrition data in getReadPermFromText

### LINKED ISSUE #72: Accessing data from "Nutrition" is not possible for anything except "Carbohydrates"
**Describe the bug**
Requesting "read" permissions for any dietary data but "Carbohydrates" doesn't work.

**To Reproduce**

```
const permissions = {
  permissions: {
    read: [
      AppleHealthKit.Constants.Permissions.ActiveEnergyBurned, // THIS IS OK
      AppleHealthKit.Constants.Permissions.BasalEnergyBurned, // THIS IS OK
      AppleHealthKit.Constants.Permissions.EnergyConsumed, 
      AppleHealthKit.Constants.Permissions.Protein,
      AppleHealthKit.Constants.Permissions.BodyMass, // THIS IS OK
      AppleHealthKit.Constants.Permissions.BodyFatPercentage, // THIS IS OK
    ],
    write: [],
  },
};
```

**Expected behavior**
After doing: 

```
AppleHealthKit.initHealthKit(permissions, (error: string) => {
  if (error) {
    console.log(error);
    console.log('[ERROR] Cannot grant permissions!');
  }
});
```

To be presented with a screen that includes the permissions requested (and described in the `permissions` array).

**Screenshots**
Here's a screenshot of code & emulator:
screenshot

**Smartphone (please complete the following information):**

- Device: Simulator:  iphone 12 mini
- OS: 14.4
- Version idk

**Additional context**
I copy pasted all available permission constants in this package and the only one that worked was "Carbohydrates".

Also **thank you for this package**! I am not very familiar with iOS development, but if Carbohydrates work, I think I can try helping fix this problem, given it's a bug and not missconfiguration by me...

### PR DESCRIPTION
**Pull request by fakeheal**
## Description

Includes proper keys for read permissions in `getReadPermFromText` regarding Nutrition Data stored in Health.

Fixes #72

### CODE REVIEW

**Comment by Macelai** [comment]
Hey @fakeheal, thanks for your contribution! 🚀

**Review by Macelai — APPROVED** [review]

File: RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m [hunk 1]
```diff
@@ -64,10 +64,84 @@ - (nullable HKObjectType *)getReadPermFromText:(nonnull NSString*)key {
...
+        return [HKObjectType quantityTypeForIdentifier:HKQuantityTypeIdentifierDietaryVitaminD];
+    } else if ([@"VitaminE" isEqualToString:key]) {
+        return [HKObjectType quantityTypeForIdentifier:HKQuantityTypeIdentifierDietaryVitaminE];
+    } else if ([@"VitaminK" isEqualToString:key]) {
+        return [HKObjectType quantityTypeForIdentifier:HKQuantityTypeIdentifierDietaryVitaminK];
+    } else if ([@"Zinc" isEqualToString:key]) {
+        return [HKObjectType quantityTypeForIdentifier:HKQuantityTypeIdentifierDietaryZinc];
+    } else if ([@"Water" isEqualToString:key]) {
+        return [HKObjectType quantityTypeForIdentifier:HKQuantityTypeIdentifierDietaryWater];
+    } else if ([@"BloodGlucose" isEqualToString:key]) {
```
Comment (lucaspbordignon) [inline RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m:143]: We already have the `BloodGlucose` at line 171. We can remove that one and stick with the new entry you've added, as that keeps it more organized

What do you think?

**Review by lucaspbordignon — CHANGES_REQUESTED** [review]
Hey @fakeheal !

Thank you so much for the contribution, that is definitively valuable when reading nutrition data 🚀 

Added a minor comment to it, but looks great on my end

File: RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m (hunk 1 above)
Comment (fakeheal) [reply RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m:143]: @lucaspbordignon I agree. Can you assist m, though? 😅 

When I visit my repository @ this branch, I have: 

> This branch is 1 commit ahead, 28 commits behind agencyenterprise:master.

Should I update the branch first and then make this change or directly push my changes to my branch? 

Thanks in advance!

Comment (Macelai) [reply RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m:143]: You could push your changes to your branch

Comment (lucaspbordignon) [reply RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m:143]: As @Macelai stated, you could just push to your branch and it will update the PR (as you already did  🙂)

**Review by lucaspbordignon — APPROVED** [review]
